version: '3'

services:
  web:
    container_name: web
    build: ./src/web
#    ports:
#          - 80:80
#          - 9000:9000
    networks:
          - back


  nginx:
    container_name: nginx
    image: nginx:1.19.2-alpine
    ports:
          - 8888:8888
    volumes:
          - ./src/nginx-front:/etc/nginx/conf.d
          - ./logs:/var/log/nginx
    links:
          - "web"
    depends_on:
          - "web"
    networks:
          - front
          - back

networks:
    front: {}
    back: {}
